package com.techprimers.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.*;

@ToString
@NoArgsConstructor
@AllArgsConstructor
@Data
@Builder
@DynamoDBTable(tableName = "payment")
public class Payment {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String paymentId;

    @DynamoDBAttribute
    private String orderId;
    @DynamoDBAttribute
    private Integer customerId;
    @DynamoDBAttribute
    private Integer sellerId;
    @DynamoDBAttribute
    private String paymentMethod;
    @DynamoDBAttribute
    private String paymentStatus;
    @DynamoDBAttribute
    private String paymentStatusNotes;
}
